### ISSUE TITLE
Words are not merged with the separator when replace is hit

### ISSUE THREAD

**Issue by viko16** [dzcpy/transliteration#202]
在命中 replace 之后，没有正确的按 separator 去拼接

```js
slugify('几种方案', {
  replace: { 种: 'zhong' },
  separator: '-',
})
```

Expect: "ji-zhong-fang-an"
Got: "jizhong-fang-an"

**Comment by dzcpy** [comment]
I just changed the data, so now 种 is transliterated to "Zhong “ instead of "Chong ". Will fix the replace option when I have time

**Comment by dzcpy** [comment]
I've made some modifications about the replace related issues in version `2.2.0`. But for your example, I woud say it your code is better be something like this:
```js
slugify('几种方案', {
  replace: { 种: 'zhong ' },
  separator: '-',
})
```
