### ISSUE TITLE
叶海林, Xie Hai Lin vs. Ye Hai Lin

### ISSUE THREAD

**Issue by retorquere** [dzcpy/transliteration#229]
I don't speak Chinese myself, but I use this library in my software; one of my users is [reporting](https://github.com/retorquere/zotero-better-bibtex/issues/1662) that `叶海林` should transliterate to `Ye Hai Lin` rather than `Xie Hai Lin` (which is what `transliteration` gives me). Is the user correct? Is there a configuration I must choose to get one vs the other?

**Comment by dzcpy** [comment]
Yes your user is correct. I'll update it in the next version

**Comment by retorquere** [comment]
Is there a timeline for the next version? Or could I apply a patch to achieve this effect in the interim?

**Comment by dzcpy** [comment]
I'll try to get it done within 2 days

**Comment by retorquere** [comment]
Sorry to press the issue, but is it possible for me to patch this in somehow?

**Comment by retorquere** [comment]
@dzcpy sorry to bother you, but is there a timeline for a new release that includes this fix?

**Comment by dzcpy** [comment]
@renovate-bot Sorry for the delay, I've been a bit busy lately. I've fixed it in version 2.2.0

**Comment by retorquere** [comment]
Is there a timeline for when this will go up on npmjs?

**Comment by dzcpy** [comment]
@retorquere I don't know what's the problem with my account, but I was unable to upload the module to npm. It seems to be a bug on npmjs.com. I've written an email to them, waiting for their reply.

**Comment by retorquere** [comment]
Thanks -- strange, the issue with your account; I've been able to upload new versions to npmjs without issue. The github version contains the compiled assets?

**Comment by dzcpy** [comment]
No, I tried to transfer the ownership to another account, and then it failed. Now both of the two accounts doesn't have permission to upload new versions. Although on the website I can still see it's in collaborators list

**Comment by dzcpy** [comment]
@retorquere OK, the update is on npm now.

**Comment by retorquere** [comment]
Awesome, thanks for the heads up!
