### ISSUE TITLE
Include and Exclude Languages 

### ISSUE THREAD

**Issue by maleksandrov** [dzcpy/transliteration#230]
Hello,

First, I wanted to thank you for the script and the time you're dedicating to updating it.  

We are developing a different theme that is using your library. For some of them make sense to include the library, but we need one language for others. 

Is there a way to include and exclude existing languages as a configuration option?

I was checking the provided documentation, and I wasn't able to find it. 

If you have time, could you please drive me in the right direction? 

Thank you!
Happy holidays! 

Milen Aleksandrov

**Comment by dzcpy** [comment]
Hi, thanks for using this library.
I'm not excactly sure what would you like to do, but maybe you can take a look at the test file here:
https://github.com/dzcpy/transliteration/blob/51b06ba1cf99064fb178a8cd045dd4edc658f0b9/test/common/transliterate.ts#L195
And here is  the source code:
https://github.com/dzcpy/transliteration/blob/51b06ba1cf99064fb178a8cd045dd4edc658f0b9/src/common/transliterate.ts#L177
So a possible solution could be something like
```js
const originalLanguageMap = tr.setData();
const newLanguageMap = {"a": "A", /*...*/};
tr.setData({...originalLanguageMap, ...newLanguageMap},  true);
```
Hope it can solve your problem

**Comment by maleksandrov** [comment]
Hello @dzcpy,

Thank you for the quick reply. 
The solution you are providing is to create a new Language Map, but in my case, I need to cherry-pick only one language. 
Example: 
English website: Here, I'll need only the Latin
English + French website:  Here, I'll need to include the French and Latin

Instead, as a rule for configuring a webpack or something where you can choose one or more languages according to the website's needs, see the example below. 

`{
 loader: 'transliteration',
   options: {
     sourceMap: true,
     default: true, //all languages
     languageSelect: Latin, Cyrillic // selection of the language, or something like that
   }
 }`

The library you create is impressive, but it is too big to have only one website that needs it. 

If not, I'll use the approach you provide above. 

Thank you for your support and excellent work. 

Best,
Milen Aleksandrov

**Comment by dzcpy** [comment]
Hi @maleksandrov, in that case this library can't do exactly what you expected yet. I've got a plan to implement it in v3 of this module, but since I've been extremely busy, I don't expect it to happen anytime soon.
Meanwhile, you may take a look at this module instead:
https://github.com/sindresorhus/transliterate

**Comment by maleksandrov** [comment]
Thank you @dzcpy
