### ISSUE TITLE
No Emoji support

### ISSUE THREAD

**Issue by hayatae** [dzcpy/transliteration#231]
Currently, all emojis appear to be filtered out when transliteration is run on a string. Is it possible to add an option to leave emojis in-place while still transliterating the rest of the string as normal?

**Comment by dzcpy** [comment]
Hi, it's doable with a workaround. It's not quite efficient though.
For example you could write something like this:
```js
const ignore = sourceString.match(/[\u{1f300}-\u{1f5ff}\u{1f900}-\u{1f9ff}\u{1f600}-\u{1f64f}\u{1f680}-\u{1f6ff}\u{2600}-\u{26ff}\u{2700}-\u{27bf}\u{1f1e6}-\u{1f1ff}\u{1f191}-\u{1f251}\u{1f004}\u{1f0cf}\u{1f170}-\u{1f171}\u{1f17e}-\u{1f17f}\u{1f18e}\u{3030}\u{2b50}\u{2b55}\u{2934}-\u{2935}\u{2b05}-\u{2b07}\u{2b1b}-\u{2b1c}\u{3297}\u{3299}\u{303d}\u{00a9}\u{00ae}\u{2122}\u{23f3}\u{24c2}\u{23e9}-\u{23ef}\u{25b6}\u{23f8}-\u{23fa}]/ug)
transliterate(sourceString, { ignore })
```

**Comment by hayatae** [comment]
Aah, I hadn't thought of using a regex like that. The `emoji-regex` (https://www.npmjs.com/package/emoji-regex) package works well for this. Might not be efficient, but it does work! Thanks.

**Comment by dzcpy** [comment]
Sure, emoji-regex is a better choice :)
