### ISSUE TITLE
`OptionsTransliterate` and `OptionsSlugify` interfaces not available Node.js

### ISSUE THREAD

**Issue by severinsimmler** [dzcpy/transliteration#234]
It would be quite useful to use the `OptionsTransliterate` and `OptionsSlugify` interfaces (this was actually possible in v1), but they are not exported and thus not available in Node.js.

**Comment by dzcpy** [comment]
Sorry for the very late reply! It should work in version `2.3.0`. If not, let me know.

**Comment by dzcpy** [comment]
It's added in version `2.3.5`

**Comment by severinsimmler** [comment]
Perfect, thank you!
