### ISSUE TITLE
[Vue warn]: Error in render function: "ReferenceError: 'Symbol' is undefined" in IE

### ISSUE THREAD

**Issue by Octane** [dzcpy/transliteration#47]
This script doesn't work in IE, because `Symbol` is undefined.
Reproduced at http://rawgit.com/andyhu/transliteration/master/demo/example.html

**Comment by Garviell** [comment]
This is quite annoying..  Especially seeing how half of the damn NPM page goes into talking about how well it works on different browsers.

**Comment by danielsig** [comment]
Symbol is an ES6 feature, which means transliteration does not work on any version of Internet Explorer.
Symbol is used in [lib/browser/transliteration.js](https://github.com/andyhu/transliteration/blob/e99a171e9e8a680a1e591ba593477f0abf8837a3/lib/browser/transliteration.js#L184) at line 184
@andyhu I suggest adding a polyfill or somehow patch this up manually.

**Comment by andyhu** [comment]
Hi guys, sorry for the late reply. I don't think it was related to transliteration module itself, I've tested it even under IE6. It's probably Vue and element-ui which don't work well in IE. If you still think there's an issue with this module, please provide some test scenarios

**Comment by Octane** [comment]
This issue reproduces without Vue.

**Comment by danielsig** [comment]
There is no support for Symbols in IE, how could your demo, which uses the Symbol class, magically work in a version of IE that was releases when Symbol was not even a draft?
It's likely skipping that line of code or something shady. Test it again, in IE 11, you'll see.
http://kangax.github.io/compat-table/es6/#test-Symbol

**Comment by danielsig** [comment]
Sorry if I come off as a bit aggressive. Here's a tiny polyfill I made that only covers the things that Transliteration needs. Maybe it can be incorporated into the actual thing?
In the very least this should fix the issues for those that are having this problem.

```javascript
if(!Symbol)
{
	var Symbol = function(){};
	Array.prototype[Symbol.iterator = "@@iterator"] = function()
	{
		var i = -1;
		var arr = this;
		return {
			next: function()
			{
				i++;
				return {
					value: arr[i],
					done: i >= arr.length
				};
			},
			return: function()
			{
				return true;
			}
		};
	}
}
```

**Comment by andyhu** [comment]
Hi, sorry for the inconvenience of this bug. I've done a bit of investigation and found that it's added automatically by babel, check https://github.com/babel/babel-preset-env/issues/203
I'll try to fix it ASAP.

**Comment by danielsig** [comment]
Don't be sorry, it's not your fault. This is all Microsoft's fault for being too incompetent to realize that they can actually design their internet dependent software to **actually use the internet to also update itself automatically**. My conclusion is that they are either a group of derps, trolls, or some combination of the two.

**Comment by andyhu** [comment]
I think I would probably create two or more distributions, 1 for all modern browsers and one for the old ones like IE. How do you guys think about it?

**Comment by danielsig** [comment]
Just use the polyfill I made, it's simplest.

**Comment by Garviell** [comment]
That just depends on what you think will be less work, you could also just add another repo that is a compatibility pack with polyfils and such.  I don't really mind as long as there is a version that is tested and works.  Thankfully IE is slowly dying so this won't be a problem forever.

**Comment by dzcpy** [comment]
I've managed to upgrade the module to v2. It's been nearly a complete rewrite. Now it should work find in IE 9+
