### ISSUE TITLE
RequireJS support

### ISSUE THREAD

**Issue by StepanPalaxo** [dzcpy/transliteration#48]
Hello, I've been trying to use transliteration in browser via [RequireJS ](http://requirejs.org) but to no avail.

When I inspected the [dist/browser/transliteration.js](https://github.com/andyhu/transliteration/blob/master/lib/browser/transliteration.js#L232-L235), I found out that the CommonJS support just doesn't do the job. On the other hand, when I tried adding
```
define(function(require, module, exports) {
        return {
            transliterate: _.transliterate,
            slugify: _.slugify
        }
    });
```
after line 223, RequireJS was able to give me what I needed.

Is it possible to check if this approach doesn't break anything and add it to production?

**Comment by StepanPalaxo** [comment]
We've also just discovered that it is possible to make RequireJS work with current build by pointing requireConfig of individual modules to built file, eg: 
```
require.config({
    paths: {
        'transliterate': '../bower_components/transliteration/lib/browser/transliteration',
        'slugify': '../bower_components/transliteration/lib/browser/transliteration',
    }
});
```
and in place of usage requiring individual functions from the module like this:
```
define(['transliterate', 'slugify'], function(transliterate, slugify) {
// ...
});
```
though in my opinion, this is not a way to go because
- in general this way you have to require N modules from one file
- module names specified at definition may lead to name collisions

**Comment by andyhu** [comment]
Apologize for the late reply. I haven't used much of RequireJS so I'm not quite sure how it works. If your solution works, would you please provide a PR?

**Comment by kranack** [comment]
Works well for me with this configuration

```
require.config({
  paths: {
    transliteration: "lib/transliteration/transliteration.min", // 1.6.2 bower install transliteration@1.6.2
  }
});

...


require(['transliteration', 'slugify'], function(transliteration, slugify) {
  // Use slugify & transliteration here
});
```
