### ISSUE TITLE
Incorrect transliteration of Bulgarian

### ISSUE THREAD

**Issue by webfacebg** [dzcpy/transliteration#56]
We tried the module for transliterating/slugging Bulgarian, but it turns out it transliterates it as Russian. There is a difference in the pronunciation of some symbols as follows:

1. For Russian [1] it is:
```
ц: "c"
щ: "shch"
ъ: ""
```
2. For Bulgarian [2] it is:
```
ц: "ts"
щ: "sht"
ъ: "a"
```
Can you give a solution how we can solve this?

[1] https://en.wikipedia.org/wiki/Romanization_of_Russian
[2] https://en.wikipedia.org/wiki/Romanization_of_Bulgarian

**Comment by andyhu** [comment]
For now, there is a temporary solution.

```js
const map = tr.setCodemap();
map['щ'.charCodeAt(0)] = 'sht';
tr.setCodemap(map);
tr('щ'); // sht
```

I know this is ugly, but it requires a bit of work to refactor the code and I'm not having enough time working on it.

**Comment by dzcpy** [comment]
Now with v2, you could probable use this method to fix it:
```
transliterate.setData({
  ц: "ts",
  щ: "sht",
  ъ: "a",
  ...
});
transliterate('цщъ');
```
