### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by vitaliyhayda** [dzcpy/transliteration#91]
In any v2 version I'm getting:

    Uncaught TypeError: Object(...) is not a function

With this simple example:

    import { transliterate } from 'transliteration';
    console.log(transliterate('bla bla'));

-------

_no issues in 1.6.6_

**Comment by dzcpy** [comment]
Hi, where did you see this error, in the browser or node.js? What's your browser / node.js version?

**Comment by dzcpy** [comment]
I've tested your code under both node.js + babel with preset-env and typescript. Can't reproduce your issue. I'll close it now but if you could elaborate how to reproduce it, feel free to open it again.

**Comment by vitaliyhayda** [comment]
works now 👍
