### ISSUE TITLE
Placeholder option doesn't seem to be honored

### ISSUE THREAD

**Issue by waldyrious** [dzcpy/transliteration#97]
What I tried:

    $ transliterate -u '_' 'foo💩bar'

Expected result:

    foo_bar

Actual result:

    foobar

Version:

    $ transliterate --version
    2.1.3

Am I perhaps misunderstanding the documentation?

**Comment by segeda** [comment]
PR #103

**Comment by waldyrious** [comment]
Fixed in #103.
